# TODO: update image name to final version from Dcokerhub
version: "3.3"
services:
  service:
    build: .
    image: taproject:v.0.5
    command: uvicorn main:app --host 0.0.0.0 --port 8898
    ports:
      - "8898:8898"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/dashboards:ro

volumes:
  grafana_storage: {}
